// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvhrqfqlcnjbylpopkkn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2aHJxZnFsY25qYnlscG9wa2tuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIyMjEzMjUsImV4cCI6MjA4Nzc5NzMyNX0.rjCc6kRdXYizO2qmYY5M40PSsHJUCiTjdxyVvq7Yrgc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});